export enum PRODUCT_CATEGORY {
  TELECOMMUNICATIONS = 'TELECOMMUNICATIONS',
  SATELLITE_INTERNET = 'SATELLITE_INTERNET',
  AUTOMATION = 'AUTOMATION',
  HOME_AUTOMATION = 'HOME_AUTOMATION',
  SMART_HOME = 'SMART_HOME',
  WEB_PLATFORM = 'WEB_PLATFORM',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  DIGITAL_EXPANSION = 'DIGITAL_EXPANSION',
}
